### ISSUE TITLE
Release cee-one.c as compilable with only cee.h

### ISSUE THREAD

**Issue by mlite** [cee-studio/cee-std#4]
cee-one.c still include some headers files.  It cannot be copied to any project to build.   

All the header files should be cloned in cee-one.c so it can compile with only cee.h

**Comment by mlite** [comment]
The same for cee-json-one.c

**Comment by mlite** [comment]
the `release` target of cee-std does not exist. It should generate a cee-one.c that can compile with cee.h only.

**Comment by mlite** [comment]
This is a regression caused by reimplementing the cee-one.c target.

**Comment by mlite** [comment]
Please restore to the original implementation like the following as `awk` wont  work for our case. 
 
```
define cee_amalgamation
	@echo "#define CEE_AMALGAMATION" > tmp.c
	@for ii in $(CEE_SRC); do echo '#include "'$$ii'"' >> tmp.c; done
	@echo "#ifndef CEE_ONE" > $(1)
	@echo "#define CEE_ONE" >> $(1)
	@echo "#define _GNU_SOURCE" >> $(1)
	@for ii in $(HEADERS); do echo '#include <'$$ii'>' >> $(1); done
	@cat cee.h >> $(1)
	@echo " " >> $(1)
	@cat cee-internal.h >> $(1)
	$(CC) -E -CC $(2) -nostdinc tmp.c >> $(1)
	@echo "#endif" >> $(1)
endefdefine cee_amalgamation
	@echo "#define CEE_AMALGAMATION" > tmp.c
	@for ii in $(CEE_SRC); do echo '#include "'$$ii'"' >> tmp.c; done
	@echo "#ifndef CEE_ONE" > $(1)
	@echo "#define CEE_ONE" >> $(1)
	@echo "#define _GNU_SOURCE" >> $(1)
	@for ii in $(HEADERS); do echo '#include <'$$ii'>' >> $(1); done
	@cat cee.h >> $(1)
	@echo " " >> $(1)
	@cat cee-internal.h >> $(1)
	$(CC) -E -CC $(2) -nostdinc tmp.c >> $(1)
	@echo "#endif" >> $(1)
endef
```

**Comment by mlite** [comment]
Can you please also add the target to build each .c file individually?

**Comment by mlite** [comment]
can you please also convert this https://github.com/cee-studio/cee-std/blob/6bc93ecc1d89534e3cdd95cfe78c1683766b5b89/cee-json/Makefile#L22   to the same method?

**Comment by mlite** [comment]
> Can you please also add the target to build each .c file individually?

Can you add this too make sure the code can be built with each .c file?

**Comment by LucasMull** [comment]
Like a generic compilation target?

**Comment by LucasMull** [comment]
Should `make` compile with each .c file, and `make release` compile the one-file target?

**Comment by mlite** [comment]
It's about adding another target so each .c  can be compiled to .o,  and these .o files are then linked to the tester executable.

**Comment by LucasMull** [comment]
This is done.
