### ISSUE TITLE
support int64_t/uint64_t

### ISSUE THREAD

**Issue by mlite** [cee-studio/cee-std#5]
`double` is too generic and cannot be print out as string consistently.  We need to support `int64_t/uint64_t` directly.

**Comment by mlite** [comment]
The function signatures
```
extern struct cee_json* cee_json_i64_mk (struct cee_state*, int64_t); 
extern struct cee_json* cee_json_u64_mk(struct cee_state*, uint64_t);
```

**Comment by mlite** [comment]
I will work on this.

**Comment by mlite** [comment]
I have split  number to double, int64_t, and uint64_t, but the parser need to parse number strings to the best number type.  Can you please enhance parser_number to detect the different number types?

**Comment by LucasMull** [comment]
> I have split  number to double, int64_t, and uint64_t, but the parser need to parse number strings to the best number type.  Can you please enhance parser_number to detect the different number types? 

Sure, I have an idea of how to do it

**Comment by LucasMull** [comment]
It's done.
